// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PreventReloadOnSelectController from "./prevent_reload_on_select_controller"
application.register("prevent-reload-on-select", PreventReloadOnSelectController)

import FadeOutController from "./fade_out_controller"
application.register("fade-out", FadeOutController)
